services:
  - type: web
    name: technogrowth-backend
    runtime: python
    rootDir: Technogrowth-Backend        
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app